language: python

python:
  - "3.6"
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
  - docker build -t marcelomaia/portal_uniforme_backend .
  - docker run -d -p 8000:8000 marcelomaia/portal_uniforme_backend python manage.py runserver --settings=config.settings.local
  - docker ps -a

deploy:
  provider: script
  script: bash utility/deploy_dockerhub.sh
  on:
    all_branches: true