language: python

python:
  - "3.6"

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - pip install -r requirements/local.txt
        - pytest
    - stage: deploy
      script: 
        - docker build -t marcelomaia/portal_uniforme_backend .
        - docker run -d -p 8000:8000 marcelomaia/portal_uniforme_backend python manage.py runserver --settings=config.settings.local
        - docker ps -a
        - bash utility/deploy_dockerhub.sh