language: python
services:
  - postgresql
  - redis-server

python:
  - "3.6"
stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      env:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=12345qw
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
        - POSTGRES_DB=uniformes
        - SENTRY=""
        - GEOREF_API_URL=""
      script:
        - psql -c "CREATE DATABASE test;" -U postgres
        - psql -c "CREATE USER admin WITH PASSWORD '12345qw';" -U postgres
        - pip install -r requirements/local.txt
        - pytest
    - stage: deploy
      script: 
        - docker build -t marcelomaia/portal_uniforme_backend .
        - docker run -d -p 8000:8000 marcelomaia/portal_uniforme_backend python manage.py runserver --settings=config.settings.local
        - docker ps -a
        - bash utility/deploy_dockerhub.sh