FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        libpq-dev \
        libcairo2 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements /tmp/requirements

RUN pip install --upgrade "pip<24.1" && \
    pip install --requirement /tmp/requirements/local.txt && \
    apt-get purge -y gcc g++ && \
    apt-get autoremove -y

COPY . /app

EXPOSE 8000