# Generated by Django 2.2.9 on 2020-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0009_loja_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='foto_fachada',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto da fachada da loja'),
        ),
    ]
