# Generated by Django 2.2.9 on 2020-02-05 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('proponentes', '0010_loja_foto_fachada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proponente',
            name='meios_de_recebimento',
        ),
    ]
