# Generated by Django 2.2.9 on 2020-02-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proponentes', '0012_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='anexos', to='proponentes.TipoDocumento'),
        ),
    ]
