# Generated by Django 2.2.9 on 2020-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0013_anexo_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nome',
            field=models.TextField(max_length=600, unique=True, verbose_name='Tipo de documento'),
        ),
    ]
