# Generated by Django 2.2.9 on 2020-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0014_auto_20200213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nome',
            field=models.TextField(unique=True, verbose_name='Tipo de documento'),
        ),
    ]
