# Generated by Django 2.2.9 on 2020-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0016_auto_20200220_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
