# Generated by Django 2.2.9 on 2020-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0018_auto_20200227_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BLOQUEADO', 'Bloqueado'), ('EM_PROCESSO', 'Pré-cadastro')], default='EM_PROCESSO', max_length=15, verbose_name='status'),
        ),
    ]
