# Generated by Django 2.2.9 on 2020-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0019_auto_20200309_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BLOQUEADO', 'Bloqueado'), ('EM_PROCESSO', 'Pré-cadastro'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('CREDENCIADO', 'Credenciado')], default='EM_PROCESSO', max_length=15, verbose_name='status'),
        ),
    ]
