# Generated by Django 2.2.9 on 2020-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0020_auto_20200309_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
