# Generated by Django 2.2.9 on 2020-07-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0021_auto_20200323_1225'),
        ('proponentes', '0021_auto_20200608_1037'),
    ]

    operations = [
    ]
