# Generated by Django 2.2.9 on 2020-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0024_proponente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proponente',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
