# Generated by Django 2.2.9 on 2020-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0026_auto_20200922_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tem_data_validade',
            field=models.BooleanField(default=False),
        ),
    ]
