# Generated by Django 2.2.9 on 2020-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0027_auto_20200924_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=15, verbose_name='status'),
        ),
    ]
