# Generated by Django 2.2.9 on 2021-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0028_auto_20200924_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='obrigatorio_sme',
            field=models.BooleanField(default=False),
        ),
    ]
