# Generated by Django 2.2.9 on 2022-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0030_loja_comprovante_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='comprovante_endereco',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Comprovante de Endereço'),
        ),
    ]
