# Generated by Django 2.2.9 on 2026-09-28 13:34

from django.db import migrations, models
import sme_uniforme_apps.proponentes.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0034_altera_status_ia_aberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listanegra',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[sme_uniforme_apps.proponentes.models.validators.cnpj_validation], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[sme_uniforme_apps.proponentes.models.validators.cnpj_validation], verbose_name='CNPJ'),
        ),
    ]
