# Generated by Django 2.2.9 on 2026-05-31 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proponentes", "0034_altera_status_ia_aberto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TriadeLote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_batch_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("submission_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "analysis_desk_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "schema_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "decisao_parecer",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("parecer_texto", models.TextField(blank=True, null=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmado_por",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payload_envio", models.TextField(blank=True, null=True)),
                ("metadata", models.TextField(blank=True, null=True)),
                ("resposta_criacao", models.TextField(blank=True, null=True)),
                (
                    "status_http_criacao",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("resposta_inicio", models.TextField(blank=True, null=True)),
                (
                    "status_http_inicio",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ultimo_erro", models.TextField(blank=True, null=True)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("callback_recebido_em", models.DateTimeField(blank=True, null=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "proponente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triade_lotes",
                        to="proponentes.Proponente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote TRIADE",
                "verbose_name_plural": "Lotes TRIADE",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="TriadeDocumento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_document_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("document_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "external_document_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("decisao", models.CharField(blank=True, max_length=20, null=True)),
                ("justificativa", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("metadata", models.TextField(blank=True, null=True)),
                (
                    "anexo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triade_documentos",
                        to="proponentes.Anexo",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="triade.TriadeLote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento TRIADE",
                "verbose_name_plural": "Documentos TRIADE",
                "ordering": ("-criado_em",),
                "unique_together": {("lote", "external_document_id")},
            },
        ),
        migrations.CreateModel(
            name="TriadeCallback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("delivery_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "external_batch_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("batch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "submission_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "assinatura_recebida",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payload_bruto", models.TextField(blank=True, null=True)),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status_processamento",
                    models.CharField(default="recebido", max_length=30),
                ),
                ("erro", models.TextField(blank=True, null=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callbacks",
                        to="triade.TriadeLote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Callback TRIADE",
                "verbose_name_plural": "Callbacks TRIADE",
                "ordering": ("-criado_em",),
            },
        ),
    ]
