# Generated by Django 2.2.9 on 2026-06-02 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("triade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TriadeConfiguracao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("habilitado", models.BooleanField(default=True)),
                (
                    "enviar_apenas_documentos_obrigatorios",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "Configuracao TRIADE",
                "verbose_name_plural": "Configuracoes TRIADE",
            },
        ),
        migrations.CreateModel(
            name="TriadeEstatistica",
            fields=[],
            options={
                "verbose_name": "Estatistica TRIADE",
                "verbose_name_plural": "Estatisticas TRIADE",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("triade.triadelote",),
        ),
    ]
