# Generated by Django 2.2.9 on 2020-02-05 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('proponentes', '0011_remove_proponente_meios_de_recebimento'),
        ('core', '0002_meioderecebimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeioDeRecebimento',
        ),
    ]
