# Generated by Django 2.2.9 on 2020-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_delete_meioderecebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniforme',
            name='categoria',
            field=models.CharField(choices=[('MALHARIA', 'Malharia'), ('CALCADO', 'Calçados')], default='MALHARIA',
                                   max_length=10),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='quantidade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='unidade',
            field=models.CharField(choices=[('UNIDADE', 'Unidade(s)'), ('PAR', 'Par(es)')], default='UNIDADE',
                                   max_length=10),
        ),
    ]
