# Generated by Django 2.2.9 on 2020-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20200206_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforme',
            name='categoria',
            field=models.CharField(choices=[('MALHARIA', 'Peças Têxteis'), ('CALCADO', 'Calçados')], default='MALHARIA',
                                   max_length=10),
        ),
    ]
