# Generated by Django 2.2.9 on 2020-02-06 15:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200206_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('categoria_uniforme',
                 models.CharField(choices=[('MALHARIA', 'Peças Têxteis'), ('CALCADO', 'Calçados')], default='MALHARIA',
                                  max_length=10, unique=True)),
                ('preco_maximo',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço máximo')),
            ],
            options={
                'verbose_name': 'Limite da categoria',
                'verbose_name_plural': 'Limites de categorias',
            },
        ),
    ]
