# Generated by Django 2.2.9 on 2020-02-11 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20200210_1120'),
        ('core', '0003_parametros'),
    ]

    operations = [
    ]
