# Generated by Django 2.2.9 on 2020-02-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20200211_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='instrucao_normativa',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Instrução Normativa'),
        ),
    ]
