# Generated by Django 2.2.9 on 2020-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parametros_instrucao_normativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='edital',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
