# Generated by Django 2.2.9 on 2020-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200211_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitecategoria',
            name='categoria_uniforme',
            field=models.CharField(choices=[('MALHARIA', 'Vestuário'), ('CALCADO', 'Calçados'), ('KIT_VERAO', 'Kit Verão'), ('KIT_INVERNO', 'Kit Inverno')], default='KIT_VERAO', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='uniforme',
            name='categoria',
            field=models.CharField(choices=[('MALHARIA', 'Vestuário'), ('CALCADO', 'Calçados'), ('KIT_VERAO', 'Kit Verão'), ('KIT_INVERNO', 'Kit Inverno')], default='KIT_VERAO', max_length=20),
        ),
    ]
