# Generated by Django 2.2.9 on 2020-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201027_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitecategoria',
            options={'verbose_name': 'Limite e obrigatoriedade da categoria', 'verbose_name_plural': 'Limites e obrigatoriedades de categorias'},
        ),
        migrations.AddField(
            model_name='limitecategoria',
            name='obrigatorio',
            field=models.BooleanField(default=True, verbose_name='Categoria obrigatoria?'),
        ),
    ]
