# Generated by Django 2.2.9 on 2020-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201027_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitecategoria',
            name='categoria_uniforme',
            field=models.CharField(choices=[('MALHARIA', 'Vestuário'), ('CALCADO', 'Calçados'), ('KIT_VERAO', 'Kit Verão'), ('KIT_INVERNO', 'Kit Inverno'), ('KIT_UNIFORME', 'Kit Uniforme')], default='KIT_VERAO', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='uniforme',
            name='categoria',
            field=models.CharField(choices=[('MALHARIA', 'Vestuário'), ('CALCADO', 'Calçados'), ('KIT_VERAO', 'Kit Verão'), ('KIT_INVERNO', 'Kit Inverno'), ('KIT_UNIFORME', 'Kit Uniforme')], default='KIT_VERAO', max_length=20),
        ),
    ]
