# Generated by Django 2.2.9 on 2021-03-24 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201214_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='email_sme',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail núcleo.'),
        ),
    ]
