# Generated by Django 2.2.9 on 2020-09-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_validado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validado',
        ),
    ]
